title: Gumil
description: Miguel Panelo. Android Developer.
google_analytics: 
show_downloads: false
remote_theme: dashingcode/front-cover

gems:
  - jekyll-mentions
  - jekyll-remote-theme


theme: jekyll-theme-minimal