title: Gumil
email: miguelrpanelo@gmail.com
description: >-
  Random Things
baseurl: ""
url: "https://www.gumil.dev" 
twitter_username: MGLPNL
github_username:  gumil

# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"

plugins:
  - jekyll-feed
