title: Gumil
email: miguelrpanelo@gmail.com
description: >-
  Random Things
baseurl: ""
url: "https://www.gumil.dev" 
twitter_username: MGLPNL
github_username:  gumil

# Build settings
theme: jekyll-theme-basically-basic

plugins:
  - jekyll-feed
