title: Gumil
description: "Miguel Panelo. Android Engineer.\n\nMotivated by passion, driven by quality software"
author: Miguel Panelo
author_email: miguelrpanelo@gmail.com
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
