title: Gumil
description: "Miguel Panelo. Android Developer.\n\nLinkedIn: https://www.linkedin.com/in/miguelpanelo/ \n\nArchived Posts: http://gumil.github.io/archive"
author: Miguel Panelo
author_email: miguelrpanelo@gmail.com
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
